services:

  cloud-weather-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=cloud_weather_dev
      - POSTGRES_USER=cloud_weather_dev
      - POSTGRES_PASSWORD=cloud_weather_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db
    networks:
      - cloud_weather

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - cloud-weather-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - cloud_weather

volumes:
  postgres-data:
  pgadmin-data:


networks:
  cloud_weather:
    driver: bridge
